Algoritmo "QUESTAO 4"

Var
id : inteiro
Inicio
escreval ("Informe sua idade")
 leia (id)
escolha (id)

 caso 1 ate 9
 escreval ("O Plano de Saúde custará 180 reais")

 caso 10 ate 30
 escreval ("O Plano de Saúde custará 150 reais")

 caso 40 ate 60
 escreval ("O Plano de Saúde custará 195 reais")

 caso 60 ate 999
 escreval ("O Plano de Saúde custará 230 reais")

 outrocaso
 escreval ("O Plano de Saúde custará 100 reais")
 
fimescolha
 
 


Fimalgoritmo