Algoritmo "Habilitação"
Var
 idade : inteiro
 psi : caracter
 visao : caracter



Inicio
 escreval ("Digite sua idade")
leia (idade)
 escreval ("Você foi aprovado no teste psicotecnico")
leia (psi)
 escreval ("Você foi aprovado no teste de visão")
leia (visao)
se (idade >= 18) e (psi = "sim") e (visao = "sim") entao
 escreval ("Voce pode tirar sua habilitação")
senao
 escreval ("Você não pode tirar sua habilitação")
fimse





 
Fimalgoritmo